language: R
r:
  - oldrel
  - release
  - devel

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo add-apt-repository -y ppa:cran/imagemagick
  - sudo apt-get -q update
  - sudo apt-get -y install libproj-dev libudunits2-dev libgeos-dev libgdal-dev cargo libavformat-dev libavcodec-dev libavfilter-dev libavdevice-dev libmagick++-dev
  - R -e 'install.packages("devtools")'

install:
  - R -e 'devtools::install_deps(dep = T)'
  - R -e 'devtools::install_github("16eagle/basemaps")'

script:
  - R CMD build .
  - R CMD check *tar.gz --no-tests
  - R -e 'devtools::test("/home/travis/build/16EAGLE/moveVis/")'
