language: R
r:
  - oldrel
  - release
  - devel
dist: bionic

addons:
 apt:
    update: true
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
      - sourceline: 'ppa:cran/ffmpeg-3'
      - sourceline: 'ppa:cran/imagemagick'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - cargo
      - libavformat-dev
      - libavcodec-dev
      - libavfilter-dev
      - libavdevice-dev
      - libmagick++-dev

before_install:
  - R -e 'install.packages("devtools")'
  - R -e 'install.packages("covr")'

r_github_packages:
  - r-lib/covr

install:
  - R -e 'devtools::install_deps(dep = T)'

script:
  - R CMD build .
  - R CMD check *tar.gz --no-tests
  - R -e 'devtools::test("/home/travis/build/16EAGLE/moveVis/")'

after_success:
  - Rscript -e 'covr::codecov()'

