language: R
r:
  - oldrel
  - release
  - devel
dist: bionic

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo add-apt-repository -y ppa:cran/ffmpeg-3
  - sudo add-apt-repository -y ppa:cran/imagemagick
  - sudo apt-get -q update
  - sudo apt-get -y install libproj-dev libudunits2-dev libgeos-dev libgdal-dev cargo libavformat-dev libavcodec-dev libavfilter-dev libavdevice-dev libmagick++-dev
  - R -e 'install.packages("devtools")'
  - R -e 'install.packages("covr")'

r_github_packages:
  - r-lib/covr

install:
  - R -e 'devtools::install_deps(dep = T)'

script:
  - R CMD build .
  - R CMD check *tar.gz --no-tests
  - R -e 'devtools::test("/home/travis/build/16EAGLE/moveVis/")'

after_success:
  - Rscript -e 'covr::codecov()'

